name: Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/**
          retention-days: 1

  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - name: Run ESLint
        run: npm run lint:ci
      - name: Run Prettier
        run: npm run prettier:ci
      - name: Run Typescript check
        run: npm run typescript

  test_sdk_manager:
    env:
      CMDLINE_TOOLS_VERSION: latest
      COMMAND_LINE_TOOLS_VERSION: 10406996
    runs-on: ${{ matrix.os }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist
      - run: ls -la .
      - run: ls -la dist
      - run: node dist/main.mjs
      - name: Verify sdk manager installation
        run: sdkmanager --list
